# This workflow will build a Java project with Maven on every push or pull request for quick checking of incoming commits.
# Verifies only on the latest Ubuntu LTS version and JDK 8.
# Checks performance on limited amount of memory to detect extra memory consumption by throwing timeouts and memory errors.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Check

on: [push, pull_request]

jobs:
  check:

    name: Quick Check

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set environment variables
      run: |
        echo "WEEK=$(date +%U)" >> $GITHUB_ENV
        echo "DAY=$(date +%w)" >> $GITHUB_ENV
      shell: bash

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-x${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ env.WEEK }}-${{ env.DAY }}
          maven-${{ env.WEEK }}
          maven-

    - name: Maven version
      run: mvn -v

    - name: Build with Maven
      run: mvn -B
      env:
        MAVEN_OPTS: -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3
